apiVersion: v1
kind: ReplicationController
metadata:
  name: consumer-rc
  labels:
    app: consumer
spec:
  replicas: 2
  selector:
    app: consumer
  template:
    metadata:
      name: consumer-rc
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: critter/sean-consumer
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 2181
        - containerPort: 8080
        - containerPort: 9092
