apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-0-rc
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    app: kafka
  template:
    metadata:
      name: kafka-0-rc
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka-0
        image: critter/sean-kafka-0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 2181
        - containerPort: 8080
        - containerPort: 9092
