apiVersion: v1
kind: ReplicationController
metadata:
  name: producer-rc
  labels:
    app: producer
spec:
  replicas: 2
  selector:
    app: producer
  template:
    metadata:
      name: producer-rc
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: critter/sean-producer
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 2181
        - containerPort: 8080
        - containerPort: 9092
