apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-rc
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    app: zookeeper
  template:
    metadata:
      name: zookeeper-rc
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: critter/sean-zookeeper
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 2181
        - containerPort: 8080
        - containerPort: 9092
